# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
storage:
  formats:
    sqlite: true
    txt: false
    html: true # ⚠️ 邮件推送必须设为 true！
